// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: proto/receiver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 메시지 정의
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Message) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 명령 메시지
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	TargetAgentId string                 `protobuf:"bytes,3,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	Parameters    string                 `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *Command) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

var File_proto_receiver_proto protoreflect.FileDescriptor

const file_proto_receiver_proto_rawDesc = "" +
	"\n" +
	"\x14proto/receiver.proto\x12\breceiver\"\x7f\n" +
	"\aMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x93\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12&\n" +
	"\x0ftarget_agent_id\x18\x03 \x01(\tR\rtargetAgentId\x12\x1e\n" +
	"\n" +
	"parameters\x18\x04 \x01(\tR\n" +
	"parameters2?\n" +
	"\bReceiver\x123\n" +
	"\aConnect\x12\x11.receiver.Message\x1a\x11.receiver.Message(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_receiver_proto_rawDescOnce sync.Once
	file_proto_receiver_proto_rawDescData []byte
)

func file_proto_receiver_proto_rawDescGZIP() []byte {
	file_proto_receiver_proto_rawDescOnce.Do(func() {
		file_proto_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_receiver_proto_rawDesc), len(file_proto_receiver_proto_rawDesc)))
	})
	return file_proto_receiver_proto_rawDescData
}

var file_proto_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_receiver_proto_goTypes = []any{
	(*Message)(nil), // 0: receiver.Message
	(*Command)(nil), // 1: receiver.Command
}
var file_proto_receiver_proto_depIdxs = []int32{
	0, // 0: receiver.Receiver.Connect:input_type -> receiver.Message
	0, // 1: receiver.Receiver.Connect:output_type -> receiver.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_receiver_proto_init() }
func file_proto_receiver_proto_init() {
	if File_proto_receiver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_receiver_proto_rawDesc), len(file_proto_receiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_receiver_proto_goTypes,
		DependencyIndexes: file_proto_receiver_proto_depIdxs,
		MessageInfos:      file_proto_receiver_proto_msgTypes,
	}.Build()
	File_proto_receiver_proto = out.File
	file_proto_receiver_proto_goTypes = nil
	file_proto_receiver_proto_depIdxs = nil
}
